### ISSUE TITLE
Chef 12 support

### ISSUE THREAD

**Issue by mdavidn** [fifthecho/knife-cloudstack-fog#24]
Someone new to Chef might run the following commands to install `knife-cloudstack-fog`.

``` sh
#!/bin/sh
curl -L https://www.chef.io/chef/install.sh | sudo bash
sudo /opt/chef/embedded/bin/gem install knife-cloudstack-fog
/opt/chef/bin/knife --help
```

This produces a broken Chef installation. The help command dumps the following RubyGems trace. The Chef installer ships with `chef 12.3.0` and `rake 10.1.1` and activates those versions before loading `knife-cloudstack-fog 0.6.0`.

```
/opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:2104:in `raise_if_conflicts': Unable to activate knife-cloudstack-fog-0.6.0, because rake-10.1.1 conflicts with rake (~> 0) (Gem::ConflictError)
        from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1282:in `activate'
        from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems.rb:198:in `rescue in try_activate'
        from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems.rb:195:in `try_activate'
        from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:126:in `rescue in require'
        from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/knife-cloudstack-fog-0.6.0/lib/chef/knife/cloudstack_zone_list.rb:19:in `<top (required)>'
        from /opt/chef/embedded/apps/chef/lib/chef/knife/core/subcommand_loader.rb:44:in `load'
        from /opt/chef/embedded/apps/chef/lib/chef/knife/core/subcommand_loader.rb:44:in `block in load_commands'
        from /opt/chef/embedded/apps/chef/lib/chef/knife/core/subcommand_loader.rb:44:in `each'
        from /opt/chef/embedded/apps/chef/lib/chef/knife/core/subcommand_loader.rb:44:in `load_commands'
        from /opt/chef/embedded/apps/chef/lib/chef/knife.rb:127:in `load_commands'
        from /opt/chef/embedded/apps/chef/lib/chef/knife.rb:147:in `list_commands'
        from /opt/chef/embedded/apps/chef/lib/chef/application/knife.rb:198:in `print_help_and_exit'
        from /opt/chef/embedded/apps/chef/lib/chef/application/knife.rb:165:in `validate_and_parse_options'
        from /opt/chef/embedded/apps/chef/lib/chef/application/knife.rb:140:in `run'
        from /opt/chef/embedded/apps/chef/bin/knife:25:in `<top (required)>'
        from /opt/chef/bin/knife:51:in `load'
        from /opt/chef/bin/knife:51:in `<main>'
```

**Comment by fifthecho** [comment]
I've just starting working with Chef 12 and have encountered this myself. I'll dig in and see if this is a quick fix.

**Comment by fifthecho** [comment]
Okay, I've updated the gemfile to remove those dependencies and the plugin appears to be working for me with ChefDK.

Can you pull and build the gem from git and test it against your environment to see if it works for you?

**Comment by mdavidn** [comment]
I built the gem from source, and it works, but I had to install `fog` by hand. I'm testing with the `chef-client` installer rather than the full ChefDK.
